#!/usr/bin/env node

var christmascolors = ["\033[0;31m","\033[0;32m"]
var clear = "\033[H\033[2J"

while (true){
  //Get the birthday from an input in the html page.
  var Birthday = new Date("January 10, 2001")
  var today = new Date()
  var msPerDay = 24 * 60 * 60 * 1000
  var timeLeft = (today.getTime() - Birthday.getTime())
  var e_daysLeft = timeLeft / msPerDay
  var daysLeft = Math.floor(e_daysLeft)
  var e_hrsLeft = (e_daysLeft - daysLeft)*24+1
  var hrsLeft = Math.floor(e_hrsLeft)
  var e_minsLeft = (e_hrsLeft - hrsLeft)*60
  var minsLeft = Math.floor(e_minsLeft)
  var e_secsLeft = (e_minsLeft - minsLeft)*60
  var secsLeft = Math.floor(e_secsLeft)
  console.log(clear + "You are " + daysLeft + " days " + hrsLeft +" hours " + minsLeft + " minutes and " + secsLeft + " seconds old")
}
